steps:
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/my-image:${SHORT_SHA}'
      - '-f'
      - 'Dockerfile'
      - '.'
      
images:
  - 'gcr.io/$PROJECT_ID/my-image:${SHORT_SHA}'
